name: plugin build/publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        run: |
          echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
    outputs:
      version: ${{ env.VERSION }}

  build:
    needs: setup
    env:
      ARTIFACTS: ${{ github.workspace }}/artifacts
      VERSION: ${{ needs.setup.outputs.version }}
    runs-on: windows-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          ./action.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.ARTIFACTS }}/build

  release:
    needs: [setup, plugin]
    env:
      ARTIFACTS: ${{ github.workspace }}/artifacts
      VERSION: ${{ needs.setup.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: show files
        run: |
          ls ${{ env.ARTIFACTS }} -l

      - name: Checkout truemedian/luvit-bin
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'

      - name: Setup GHR
        run: |
          go get -u github.com/tcnksm/ghr
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.ARTIFACTS }}

      - name: Collect Artifacts
        run: |
          mkdir -p releases/
          cp ${{ env.ARTIFACTS }}/* releases/
      - name: Upload Plugin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghr \
            -replace \
            -n "PLUGIN / ${{ env.VERSION }}" \
            -b "깃허브 워크플로우에 의해 자동 업로드됨" \
            "${{ env.VERSION }}" releases/
