name: release

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        run: |
          echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
    outputs:
      version: ${{ env.VERSION }}

  build:
    needs: setup
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    runs-on: windows-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          ./action.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: ${{ github.workspace }}/out/*

  release:
    needs: [setup, build]
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'

      - name: Setup GHR
        run: |
          go get -u github.com/tcnksm/ghr

      - name: Download output
        uses: actions/download-artifact@v2
        with:
          name: out
          path: .\out

      - name: Upload Plugin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghr out/
            -u 살려주세요
            -replace \
            -n "PLUGIN / ${{ env.VERSION }}" \
            -b "깃허브 워크플로우에 의해 자동 업로드됨" \
