name: release

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        run: echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
    outputs:
      version: ${{ env.VERSION }}

  build:
    needs: setup
    env:
      NAME: InstallerPlugin
      INFO: src\version.txt
    runs-on: windows-latest
    steps:
      - name: Download this repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download package handler repo
        uses: actions/checkout@v2
        with:
          repository: nofairTCM/Package
          path: Package
          persist-credentials: false
          fetch-depth: 0

      - name: build / upload / update package list
        shell: cmd
        run: |
          mkdir out
          Package\bin\luvit.exe Package build --project gui.project.json --output out\nofairTCM_Installer_GUIversion.rbxmx
          Package\bin\luvit.exe Package upload --project gui.project.json --assetId ${{ secrets.SECRETS_RBLXASSET }} --cookie "${{ secrets.SECRETS_RBLXTOKEN }}"
          Package\bin\luvit.exe Package build --project cli.project.json --output out\nofairTCM_Installer_CLIversion.rbxmx
          Package\bin\luvit.exe Package upload --project cli.project.json --assetId 6912288435 --cookie "${{ secrets.SECRETS_RBLXTOKEN }}"
          Package\bin\luvit.exe Package updateList --info %INFO% --name %NAME%

      - name: push package list
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRETS_GHDBTOKEN }}
          branch: ${{ github.ref }}
          directory: Package
          repository: nofairTCM/Package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: ${{ github.workspace }}/out/*

  release:
    needs: [setup, build]
    env:
      VERSION: ${{ needs.setup.outputs.version }}.${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Download output
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out

      - name: Upload Plugin Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: out/*
          name: PLUGIN / ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body: |
            CLI 버전 : 터미널만 포함된 빌드입니다, 기본적으로 GUI 보다 빠르게 로드가 가능하며 가볍습니다
            GUI 버전 : 인터패이스가 포함된 빌드입니다, 더 친숙한 조작이 가능합니다 (초보자의 경우 이 버전을 추천합니다)

            CLI 가 GUI 보다 용량 단위로는 15 배 정도 가볍고 로드속도로는 5~10 배 정도 빠릅니다
            필요에 따라 골라서 사용하세요

            CLI 버전은 여기에서도 설치가 가능합니다 https://www.roblox.com/library/6912288435/nofairTCM-Installer-CLI
            GUI 버전은 여기에서도 설치가 가능합니다 https://www.roblox.com/library/6801472559/nofairTCM-Installer

            더 많은 정보를 얻으려면 README.md 를 확인해주세요

            [이 빌드는 github workflows 에 의해 생성되었습니다] 
