name: release

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 5 * * *'
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        run: echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
    outputs:
      version: ${{ env.VERSION }}

  build:
    needs: setup
    env:
      VERSION: ${{ needs.setup.outputs.version }}
      SECRETS_RBLXASSET: ${{ secrets.SECRETS_RBLXASSET }}
      SECRETS_RBLXTOKEN: ${{ secrets.SECRETS_RBLXTOKEN }}
    runs-on: windows-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        shell: pwsh
        run: ./action.ps1

      - name: Publish to rblx
        shell: cmd
        run: |
          @echo off
          rojo --asset_id %SECRETS_RBLXASSET% --cookie "%SECRETS_RBLXTOKEN%"

      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: ${{ github.workspace }}/out/*

  release:
    needs: [setup, build]
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'

      - name: Setup GHR
        run: |
          go get -u github.com/tcnksm/ghr

      - name: make output dir
        run: mkdir out

      - name: Download output
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out

      - name: show status
        run: ls
      
      - name: show status2
        run: ls out

      - name: Upload Plugin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ghr -n "PLUGIN / ${{ env.VERSION }}" -b "깃허브 워크플로우에 의해 자동 업로드됨" ${{ env.VERSION }} out/
